### ISSUE TITLE
corner computation for unions etc

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#110]
Right now, you're simply gathering all corners of all constituting domains:

https://github.com/krober10nd/SeismicMesh/blob/master/SeismicMesh/geometry/signed_distance_functions.py#L41

This isn't quite accurate. For unions, you can scratch all those corners which are strictly inside the union. Similar for intersections.

**Comment by krober10nd** [comment]
Yea need to work on that. Also for periodic domains like in the open PR

**Comment by krober10nd** [comment]
So I remove corners now that are further than a threshold (1000*deps) from the 0-level set. This should get rid of the "interior" corners in the case of unions, etc.
