### ISSUE TITLE
readme examples

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#111]
The readme still lists many examples which take a function for a domain. I think it'd be nicer if those were converted to domains, too, e.g.,
```
class Torus:
    def __init__(self, x0, x1, r):
        bbox = (-r, r, -r, r, x0, x1)

    def eval(x):
        xz = np.column_stack((p[:, 0], p[:, 2]))
        q = np.column_stack((length(xz) - t[0], p[:, 1]))
        return length(q) - t[1]
```
Other than that I think the readme is great. SM looks quite capable now.

Also a tip for the figures: You can turn off the orientation axis in ParaView and trim the pngs afterwards. This way, you don't waste precious vertical room. On unix, you can trim on the command line via
```
convert -trim in.png out.png
```

**Comment by krober10nd** [comment]
Okay work in progress. Thanks for the trimming tip, yea one reason I didn't trim before was because it remains a mystery how to get images to size based on specifications on markdown text.

**Comment by nschloe** [comment]
Just use HTML syntax, e.g.,
```
  <img alt="cube" src="https://krober10nd.github.io/seismicmesh/cube.png" width="30%">
```

**Comment by krober10nd** [comment]
okay I made three new geometric primitives and updated the images for cropping and using the HTML syntax (where relevant). just waiting for the build to pass then will merge.
