### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#116]
Perhaps a CONTRIBUTING.md file can be added to the repo. [This](https://github.com/nschloe/pyfoobar/blob/master/CONTRIBUTING.md) could serve as a template.

**Comment by krober10nd** [comment]
So is this preferred instead of being located on the README (as it is now)?

**Comment by nschloe** [comment]
Nah that's fine, I overlooked it.
