### ISSUE TITLE
Inconsistent use of HMIN

### ISSUE THREAD

**Issue by jorgensd** [krober10nd/SeismicMesh#143]
As both your mesh generator, and and the build sizing function has `hmin` as an input argument, is there
any way of making a check that the input argument into these two functions matches each other?
Could you add hmin as a variable in the `SizeFunction` class, such that you do not need `hmin` as an input to generate mesh when supplying a `SizingFunction`?

**Comment by krober10nd** [comment]
You mean that the user can accidentally mispecify the `hmin` and `h0` in the `generate_mesh` command. Yea, I've had that happen. Perhaps yes, it's best to have the `SizingFunction` class contain the minimum edge length in the domain. I'll work on that. 

I'll keep `h0` as a user-defined argument and this gets the last word so to speak on what the minimum edge length value will be if it's passed but if it isn't passed, it will get it from that class. This is to maintain backwards compatibility with scripts that people are already using here.

**Comment by krober10nd** [comment]
i've dealt with this in #144 and will be released with 3.1.4. Now the user just passes a `domain` and a `SizeFunction`, the `hmin` is pulled from the `SizeFunction`.

**Comment by krober10nd** [comment]
3.1.4 is released with this change. let me know if you're okay with my changes.

**Comment by krober10nd** [comment]
I'm going to go ahead and close this for now. The `hmin` will by default match the value passed to the sizing function so there's almost no chance of error anymore.
