### ISSUE TITLE
can't install seismicmesh with python 3.8.1+

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#158]
```python
import sys

print(sys.version_info)
print(sys.version_info > (3, 8))
```
```
sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
True
```

**Comment by nschloe** [comment]
This also means that SM isn't properly tested with all supported Python versions.

**Comment by krober10nd** [comment]
Actually, I can't test 3.9 because of `segyio`. And I put in a stop to prevent installation for that exact reason.

**Comment by krober10nd** [comment]
I'll put in some more builds into the CI machine.

**Comment by nschloe** [comment]
Right now, you're also blocking 3.8.1 (which is `> (3,8)`).

**Comment by krober10nd** [comment]
oh I see your point. I was going to test other versions of Python any way too. I'll fix both.

**Comment by nschloe** [comment]
> Actually, I can't test 3.9 because of segyio

It's also my experience that Python 3.9 is a bit early for testing. Many packages aren't cached yet and tests take forever, so I still leave that out. Your mileage may vary.

**Comment by krober10nd** [comment]
Yea, it it a bit early. 

Eventually I'll switch over to Github workflows with the hope that they don't start charging.

**Comment by krober10nd** [comment]
You should be able to install now with 3.8.1. It's also tested on the CI system along with version 3.6.5.

**Comment by nschloe** [comment]
Fix confirmed.
