### ISSUE TITLE
generate_mesh() in README.md example needs h0=100

### ISSUE THREAD

**Issue by HamishB** [krober10nd/SeismicMesh#160]
generate_mesh() listed in the example fails with a missing 'h0'. Adding ", h0=100" did the trick.

**Comment by krober10nd** [comment]
Which example? Theres about 20. Which version of SeismicMesh are you on? This was not required for some time now

**Comment by HamishB** [comment]
BP2004 example, par3d branch git-pulled yesterday.

**Comment by HamishB** [comment]
or maybe if it's picking up the pip'd version, SeismicMesh-3.1.31

**Comment by krober10nd** [comment]
Ah okay. The default branch is `master` for some time now. Did you install via pip or from source?

**Comment by krober10nd** [comment]
and fyi, all the examples on the README are always going to be valid for the last master HEAD.
