### ISSUE TITLE
how to install pybind11 on Ubuntu 18.04

### ISSUE THREAD

**Issue by HamishB** [krober10nd/SeismicMesh#161]
Hi,

more of an FYI for the install pages than a bug, but for anyone else who needs to get it going, Ubuntu 18.04 LTS comes with Pybind11 version 2.0.1 and the SM build fails as it needs version 2.5 or newer. Simply downloading the two .deb packages* for Ubuntu 20.10 (Groovy) and installing them over the top of the 2.0.1 version with `dpkg` works great.

[*] python3-pybind11 and pybind11-dev
  https://packages.ubuntu.com/groovy/all/python3-pybind11/download
  https://packages.ubuntu.com/groovy/all/pybind11-dev/download

**Comment by krober10nd** [comment]
Yes, the installation requirements are listed here.

https://seismicmesh.readthedocs.io/en/par3d/install.html

It requires pybind11 >= 2.5 and CGAL >= 5.0 otherwise it cannot compile the CPP codes.
