### ISSUE TITLE
misleading license

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#19]
SeismicMesh uses the BSD-2 license. This is probably misleading. In my experience, users will be surprised to learn that they cannot use SeismicMesh under the BSD-2 only, but have to consider the licences of the dependencies too. And there you'll find CGAL with ships under the (L)GPL which restricts users much more.

I'd either 
 * change SeismicMesh license's to GPL, or
 * put a BIG FAT warning in the readme/licensing etc., or
 * remove the CGAL dependency.

**Comment by krober10nd** [comment]
Thanks for pointing that out. I have no qualms with changing to GPL and I started a PR #20  for this change.

CGAL is used in several different places that are critical for the software's functionality. I had used the wrapper of `Qhull` previously from Scipy but was ~5x times slower than CGAL and had some serious robustness issues.

**Comment by nschloe** [comment]
For the record, I did the same move with pygalmesh, see https://github.com/nschloe/pygalmesh/issues/63. The CGAL folks actually suggested it, and I was reluctant at first. It was the right thing to do though, in retrospect.

**Comment by krober10nd** [comment]
Yea, I've gotten into this trouble with other packages before. It tends to be a big issue when you aren't in academica (obviously). 

Anyway, this was addressed in the merged #20. Feel free to close it if you are satisfied.

**Comment by nschloe** [comment]
You should also specify
```
license = GPL-3.0-or-later
license_file = LICENSE.txt
```
in `setup.py`. (This way, it gets packaged properly.)

**Comment by krober10nd** [comment]
Looks like ``license_file`` isn't a thing for `setup.py` but is for `setup.cfg`.  When I went to add `license_file` to `setup.py` and then ran `python setup.py check` it said 

`UserWarning: Unknown distribution option: 'license_file'`

 This stack-overflow thread sure is confusing about it...https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script 

Maybe should create a `setup.cfg` I guess?

**Comment by nschloe** [comment]
> Maybe should create a setup.cfg I guess?

Ah yes, that's what I used to do. (Almost always ditching `setup.py` entirely now, but that's not possible with compiled sources.)

**Comment by krober10nd** [comment]
Ok, so I switched to setup.cfg file that should package the license with the sdist build.

**Comment by nschloe** [comment]
Very cool. Is `requirements.txt` still needed actually? Never really sure here.

**Comment by krober10nd** [comment]
I'm also not too sure either. I think ``requirements.txt`` could be still used if you want to do something like look back at what I was using if some kind of dependency problem was encountered later on. 

In that case, I could add in more of the version numbers into it as some are missing now.

**Comment by nschloe** [comment]
Fair enough.
