### ISSUE TITLE
new pybind11

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#203]
pybind11 got a great little update a few months ago that helps reducing the boilerplate code. You just add an entry to `pyproject.toml` and then you can use `Pybind11Extension` in your `setup.py`. Check out [pygalmesh](https://github.com/nschloe/pygalmesh).

**Comment by krober10nd** [comment]
Great, I'll deal with this after I resolve the issues with 3.9. 

 I have to say that was perhaps the trickiest part of setting up a mixed C++ Python package. Figuring out which boilerplate code you need.

**Comment by nschloe** [comment]
Tell me about it, I've gone through it too. Argh! The new helpers are nifty and I'm happy I don't have to deal with the compiler flags anymore.

**Comment by krober10nd** [comment]
This is on my to do list finally. By the way, I’ve had a bunch of people try to install SM on Linux based machines and they always go for the sudo apt get install cgal route which installs an ancient version of cgal being installed that prevents the installation of SM.
