### ISSUE TITLE
exdown no longer is maintained

### ISSUE THREAD

**Issue by krober10nd** [krober10nd/SeismicMesh#212]
@nschloe I'm running into some issues with `exdown` which appears to be deprecated and disappeared from your github. 

suggestions on what to use instead?

**Comment by nschloe** [comment]
You can still use it, it'll be there for a long while. I'm working on a better alternative though, eta tomorrow.

**Comment by krober10nd** [comment]
Thanks Nico. Good to know. I am very dependent on your codes :)

**Comment by nschloe** [comment]
There's https://github.com/nschloe/pytest-codeblocks now.

**Comment by krober10nd** [comment]
Thanks! I’ll switch it over this weekend hopefully.

**Comment by krober10nd** [comment]
#213
