### ISSUE TITLE
pyamg == 4.0.0?

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#217]
The pyamg dependency is fixed to 4.0.0. Why?

**Comment by krober10nd** [comment]
Some users were reporting the call to the AMG seg faulting on Ubuntu systems. Never had this issue on Mac.

**Comment by nschloe** [comment]
Hm, that's weird. Perhaps you should exclude certain versions then. Fixing the dependency makes it difficult to work with newer pyamg versions (pip installs everything globally).

**Comment by krober10nd** [comment]
yea, I'll try that after I get workflows working. And pinning versions is not a good idea, I agree.

**Comment by krober10nd** [comment]
ah the other reason I had fixed the version of `pyamg`, is more recent versions of `pyamg` were causing my Laplacian smooths to produce widely different total number of vertices and elements and thus some tests were failing that had previously always worked. 

I'll unpin the version in #216 and we'll see where it goes wrong.

I'

**Comment by krober10nd** [comment]
No longer pinned now #216
