### ISSUE TITLE
consider using code formats

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#27]
There's the common Python formatter black; from what I see your code is already it. Also: isort for sorting the imports, and: flake8. In my project Makefile, I usually have
```Makefile
format:
>~isort .
>~black .
>~blacken-docs README.md

lint:
>~isort --check .
>~black --check .
>~flake8 .
```
Perhaps one of them is useful to you, perhaps not. Perhaps there's something similar for the C++ part of your code.

**Comment by krober10nd** [comment]
Interesting. I'm not familiar with the Makefile for a Python package. I see one of yours here https://github.com/nschloe/pygalmesh/blob/master/Makefile

When is this file used?

**Comment by krober10nd** [comment]
Looks like it provides macros to accelerate common tasks.

**Comment by nschloe** [comment]
> When is this file used?

Indeed, it's just for me to remember the command. It's basically a txt-file without having to copy-paste commands. That's a personal preference though, everyone does that differently I guess.

**Comment by krober10nd** [comment]
It's seems very useful because, I too am constantly forgetting these commands. 

I'll look into something similar for the C++

**Comment by nschloe** [comment]
One big plus of using formatting (and optionally advertising it with a badge or so) is that people see that you though about formatting and the code doesn't look horrible. It gives a good first impression and encourages contributions.

**Comment by krober10nd** [comment]
Yea, that's definitely true. Working with a good open source project like FEINCS/Firedrake team too has showed me better ways to do things (like what you suggest) that I unfortunately wasn't exposed to earlier on.

**Comment by krober10nd** [comment]
Ok, I set up a Makefile. This will definitely help when I go to add new features etc. later on. For c++, I used `clang-format` which seems to have improved the clarity of things imo.
