### ISSUE TITLE
test coverage not properly configured?

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#31]
When looking at the [coverage data](https://codecov.io/gh/krober10nd/SeismicMesh/tree/2d321a9a40fa7797c9eec28f384290b253a9df70/SeismicMesh
), I only see a few files accounted for:

![screenshot](https://user-images.githubusercontent.com/181628/91662526-60c1a280-eae3-11ea-80e9-da761be702d3.png)

It seems that there is something misconfigured. Could you look into it?

**Comment by krober10nd** [comment]
Indeed, the CI system was pointed to `master` which I don't use. I switched it to my default `par3d` branch and now the coverage report is showing a much more accurate depiction of what the tests pass through. 

<img width="1440" alt="Screen Shot 2020-08-30 at 5 50 54 PM" src="https://user-images.githubusercontent.com/18619644/91669173-5c988380-eae9-11ea-8598-98b745357f32.png">

**Comment by nschloe** [comment]
When you click on any of the files in codecov, you get a 404. I think you can remove most of the codecov config to fix this.

**Comment by krober10nd** [comment]
I see. I fixed that by making sure the codecov didn't "fix paths" 

Check it out now: 

https://codecov.io/gh/krober10nd/SeismicMesh/src/par3d/SeismicMesh/generation/mesh_generator.py

**Comment by nschloe** [comment]
Looking good now.
