### ISSUE TITLE
dependencies and test dependencies mixed up

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#32]
Some of the dependencies listed in setup.cfg are not necessary for running SeismicMesh, but really are test dependencies, for example exdown. They should be listed separately, for example in a `test_requirements.txt` file, in the circleci config, or in a `tox.ini` (should you ever use that).

**Comment by krober10nd** [comment]
Ok thanks. What do you think about if I did something like this by editing the setup.cfg file?

https://stackoverflow.com/questions/15422527/best-practices-how-do-you-list-required-dependencies-in-your-setup-py

**Comment by nschloe** [comment]
Ah, I didnt know about tests_require. If this works, awesome!

**Comment by krober10nd** [comment]
Unfortunately that approach I linked to above didn't work. `setuptools` tells you it's not a good method (you have to use `python setup.py develop` in your CI script) and it says it will be deprecated in the near future. 

Instead, I went with the more modern `tox.ini` route. I updated the CI script accordingly in #34 and included a `pyproject.toml` file and a `tox.ini` file. This now results in a clean separation of dependencies for testing and for installation. It increased the time to complete the tests to about 12 minutes but oh well.

**Comment by nschloe** [comment]
It's always worthwhile trying to keep test times down. With
```
pytest --durations=5
```
you can see the top 5 slowest tests. This always helps me out big time.

**Comment by krober10nd** [comment]
Thanks! I think it was in part due to some downloading of packages that happened to be slower yesterday. Today it passed in 9 minutes or so.
