### ISSUE TITLE
lgtm errors

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#37]
Check those out: https://lgtm.com/projects/g/krober10nd/SeismicMesh/alerts?mode=list. Some of them aren't so useful (e.g., the `rank == 0` complaints), some are.

**Comment by krober10nd** [comment]
Woah, this is amazing.

**Comment by krober10nd** [comment]
So I took a detailed look at those warnings and such (and hooked LGTM into PRs). But the majority seem to be triggered erroneously. I fixed the bunch that I thought were problematic but I'm not finding the button to trigger a new reanalysis.

**Comment by nschloe** [comment]
I think it triggers once a day or so.
