### ISSUE TITLE
snake case for variable, function names

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#48]
I'm now diving into SeismicMesh's code. One thing I've noticed is that it doesn't follow PEP8 conventions for variable/function/class names. Check https://www.python.org/dev/peps/pep-0008/#function-and-variable-names.

**Comment by krober10nd** [comment]
You mean switching between CapsCase and underscores sometimes? The style guideline was never clear to me for this as it states in several places that you can switch between CapsCase and underscores as the developer sees fit. 

 I was always of the opinion "A Foolish Consistency is the Hobgoblin of Little Mind". 

 With that said, I can make all functions the underscore with two words separated and all classes CapsCase. Variables are little bit murky.

**Comment by nschloe** [comment]
All serious Python codes follow this convention, so it's probably useful for SeismicMesh too.

> Class names should normally use the CapWords convention.

> Because exceptions should be classes, the class naming convention applies here.

> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
> Variable names follow the same convention as function names.

**Comment by krober10nd** [comment]
Fair enough. I'll make the changes.

**Comment by krober10nd** [comment]
Ok I put some effort into this today in the merged #51. If you're ok with what I've down, please let me know!

**Comment by nschloe** [comment]
Lgtm. The only notable exception I see now is `SizingFunction` in https://github.com/krober10nd/SeismicMesh/blob/par3d/SeismicMesh/generation/mesh_generator.py#L58, but it's not clear to me now if this is perhaps a class.

**Comment by krober10nd** [comment]
So I cleaned up and tagged a new release based on the new API that we discussed...

https://pypi.org/project/SeismicMesh/3.0.0/
