### ISSUE TITLE
bounding box from files?

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#50]
In the README examples, the bounding boxes are specified explicitly. Can those not be read from the segy files?

**Comment by krober10nd** [comment]
I'll look into this but my initial guess is no this information isn't always standardized in the segy format. The segy format is quite dated and is used for a variety of purposes in seismology now. It has a fixed length header with user written notes typically.

**Comment by nschloe** [comment]
I think if it contains velocity data, then there must be an indication of where the data lives, too, right?

**Comment by krober10nd** [comment]
Yea, I had thought the same but had originally given up. I'll try again. 

I started an issue with `segyio` to see if they have any insight. 

https://github.com/equinor/segyio/issues/472

The segy format is essentially overloaded to support seismic velocity models. Normally it stores these things called shot records which are essentially collections of time series at microphones along the surface of the Earth.

**Comment by nschloe** [comment]
I see: The segy format by default only contains nx, ny[, nz]. Let's wait for the segyio issue to resolve, but probably the bbox has to be specified explicitly.
