### ISSUE TITLE
JOSS: Review notes

### ISSUE THREAD

**Issue by jorgensd** [krober10nd/SeismicMesh#59]
- [x] Fix typo in affiliations: Currently: Reearch Center for Gas Innovation, should be Re**s**earch
- [x] Update install instructions. On ubuntu 20.04, there is no `python-pybind11`, only `python3-pybind11`. This should be clarified in the installation instructions.
- [x] Suggestion (not required) Using Eigen in C++ would remove quite a plot of the code converting back and forth in pybind11. See: https://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html
- [ ] Suggestion (not required): Add a Dockerfile with installation based. For example base it on the ubuntu20.04 image, to make installation easier.
More notes to come over the following days.

**Comment by krober10nd** [comment]
Thanks! I'll get to these shortly.

**Comment by krober10nd** [comment]
I'll take a closer look at the Eigen stuff with pybind11 and see if the third item is feasible in a practical time and doesn't require intrusive changes in the code stack.

 I agree in the sense that there's some code repetition to convert between Python types and C types using the existing approach.

**Comment by jorgensd** [comment]
> I'll take a closer look at the Eigen stuff with pybind11 and see if the third item is feasible in a practical time and doesn't require intrusive changes in the code stack.
> 
> 
> 
>  I agree in the sense that there's some code repetition to convert between Python types and C types using the existing approach. 

It is more of a hint for future development, rather than a requirement. As eigen <-> numpy is automatic with pybind 11, it makes things quite neat.

**Comment by krober10nd** [comment]
Hey @jorgensd do you have more comments? Things have improved in the last two weeks with the latest pull two requests or so.

**Comment by jorgensd** [comment]
> Hey @jorgensd do you have more comments? Things have improved in the last two weeks with the latest pull two requests or so.

I'll have a close look at these over the weekend. Sorry that I haven't gotten back to you soone.

**Comment by krober10nd** [comment]
Alright. no worries. Thanks!

**Comment by jorgensd** [comment]
Minor note, you have to adjust this line: https://github.com/krober10nd/SeismicMesh/blob/par3d/tests/test_2dmesher_domain_extension.py#L66
as your function requires an input argument

**Comment by jorgensd** [comment]
@krober10nd I had a look at https://github.com/krober10nd/SeismicMesh/blob/par3d/tests/test_2dmesher_domain_extension.py#L24 and when inspecting the mesh with Paraview, I observe that in several places, the mesh does not align with your 0-level set boundary. Wouldn't such inaccuracies be an issue when marking the domains after mesh generation, for application of different boundary conditions in a FEM analysis framework?
![non-aligned](https://user-images.githubusercontent.com/8554300/95678102-4985d280-0bc2-11eb-9dc4-50a8f8f99f8d.png)
![rectangle_corner](https://user-images.githubusercontent.com/8554300/95678103-4a1e6900-0bc2-11eb-90fa-436076b4a401.png)

**Comment by jorgensd** [comment]
Another question, could you set up a CI that automatically runs your tests?

**Comment by krober10nd** [comment]
in regard to the Ci that's already happening every commit and pull request. See the readme badges for the CI one and click it

**Comment by jorgensd** [comment]
> in regard to the Ci that's already happening every commit and pull request. See the readme badges for the CI one and click it

You are right, my mistake, I browsed through the build output too quickly, and didnt realize it actually runs the tests as well;)

**Comment by krober10nd** [comment]
No problem :) in regard to the dents, Nico also literally just noticed this in #82. I just want to make sure you're building the HEAD of par3d branch. You can confirm the version by SeismicMesh.__version__

**Comment by krober10nd** [comment]
GitHub changed the version thing it should be a dunder

**Comment by jorgensd** [comment]
> No problem :) in regard to the dents, Nico also literally just noticed this in #82. I just want to make sure you're building the HEAD of par3d branch. You can confirm the version by SeismicMesh.**version**

Im build of master, version 3.0.4. You can also see these issues in your readme, when generating the Boxmesh
```
import SeismicMesh
import meshio

cube = SeismicMesh.Cube((0.0, 1.0, 0.0, 1.0, 0.0, 1.0))
points, cells = SeismicMesh.generate_mesh(domain=cube, edge_length=0.05)
meshio.write_points_cells(
    "cube.vtk",
    points,
    [("tetra", cells)],
    file_format="vtk",
)
```
or just look at the png in the readme

**Comment by krober10nd** [comment]
In regard to the comment above, I tried to add an improvement step in #84

**Comment by jorgensd** [comment]
I'll test the improvement code with the code i posted in the other issue later tonight

**Comment by jorgensd** [comment]
Is there any particular reason for not using master as the default branch?

**Comment by nschloe** [comment]
I agree with @jorgensd, it's unusual to not use _master_ (or soon-to-be-default _main_) as the main development branch.

**Comment by krober10nd** [comment]
Fair enough. Changed default to master.

**Comment by jorgensd** [comment]
Some notes on the docs: Typo in headers of: https://github.com/krober10nd/SeismicMesh/blob/master/docs/source/usrman/api.rst#seimsicmeshgeometry
Consistent capitalization in: https://github.com/krober10nd/SeismicMesh/blob/master/docs/source/usrman/intro.rst#introduction (Finite Element and Finite volume).

**Comment by jorgensd** [comment]
@krober10nd Is there any reason for the `testing.segy` file in the `tests`-folder cannot be visualized with Paraview?
Just out of interest, what visualization module do you use for segy files?

**Comment by krober10nd** [comment]
Ah segy is an ancient format that seismologists use (basically binary with a header) that stores something called shot records. I'm afraid ParaView may not be able to read this in. 

I visualize the files using [segyio](https://github.com/equinor/segyio) and then plot in Python using matplotlib...

In 2D you can read in a velocity model packed in a segy file using these lines of code...

https://github.com/krober10nd/SeismicMesh/blob/b504b5255cb4bd3776235fef0ad9ee7e8fec37d7/SeismicMesh/sizing/mesh_size_function.py#L544

**Comment by krober10nd** [comment]
For 3D,  the industry packs these gridded seismic data traditionally in binary files in a FORTRAN/C memory layout hence why I have options to specify that packing format in 3D.

**Comment by jorgensd** [comment]
> Ah segy is an ancient format that seismologists use (basically binary with a header) that stores something called shot records. I'm afraid ParaView may not be able to read this in.
> 
> I visualize the files using [segyio](https://github.com/equinor/segyio) and then plot in Python using matplotlib...
> 
> In 2D you can read in a velocity model packed in a segy file using these lines of code...
> 
> https://github.com/krober10nd/SeismicMesh/blob/b504b5255cb4bd3776235fef0ad9ee7e8fec37d7/SeismicMesh/sizing/mesh_size_function.py#L544

In theory (see the link I added in the previous post) Paraview should be able to view segy files.

**Comment by krober10nd** [comment]
Interesting. I'll try it out later today. I wasn't aware of this module inside ParaView.

**Comment by jorgensd** [comment]
As a side note, you should add a **Contributing** section to the readme. Similar to:
https://github.com/dolfin-adjoint/pyadjoint/#contributing

**Comment by krober10nd** [comment]
So I'm not sure why the test.segy file doesn't get read into ParaView, but some of the other test files (like the one in the 2D one in the examples) works just fine:

![BP2004_ss](https://user-images.githubusercontent.com/18619644/96925127-10831300-148a-11eb-9188-f7cc31596095.png)

**Comment by krober10nd** [comment]
BTW, I added the contributing section. 

And I'm investigating the test.segy file.

**Comment by krober10nd** [comment]
Hey Jorgen just an update. I tried to write the testing.segy file using `segyio` with the hopes that the ParaView visualization issue was related to the header of the file but unfortunately it did not work. 

This is what I tried

```
 import numpy as np
 import segyio
 
 filename = "testing.segy"
 with segyio.open(filename, ignore_geometry=True) as f:
     nz, nx = len(f.samples), len(f.trace)
     vp = np.zeros(shape=(nz, nx))
     for index, trace in enumerate(f.trace):
         vp[:, index] = trace
 
 
 spec = segyio.spec()
 spec.tracecount = nx
 spec.samples = list(range(nz))
 spec.format = 1
 output_file = "testing2.segy"
 with segyio.create(output_file, spec) as src:
     for index in range(nx):
         src.trace[index] = vp[:, index]
```

when testing2.segy goes into ParaView, I get an insta-crash.

**Comment by jorgensd** [comment]
No worries, I was just curious.

**Comment by krober10nd** [comment]
Hey @jorgensd just letting you know that I recently improved my analysis of SM's parallel performance with both a light (~4M cells) and heavy (33M cells) version of a 3D model, produced a new figure and updated the paper.

**Comment by jorgensd** [comment]
In the *Background* section of the paper, you use the abbreviation RTM for Reverse Time Migration, but this abbreviation does not appear elsewhere in the paper. I would thus remove it.

**Comment by jorgensd** [comment]
There also to be a mismatch between the section **Performance comparison** and the figure.
 ```
For the two seismic meshes (e.g., BP2004 and EAGE), SeismicMesh is faster than cgal but slower than gmsh and the mesh quality similarly follows the results observed in the analytical cases.
```
On the case of BP2004 there is no plot for CGAL, and GMSH is slower than Seismicmesh 
The statement is only true for the EAGE mesh.

I would also like a consistent use of x-ticks of the number of cells. 
i.e.Use either the format  0.5, 1, 1.5 1e6 as done for the BP mesh for all other meshes (1e5 for the EAGE mesh).

The ticks labels and titles for each mesh is still way too small (I printed it again). Instead of having a 2x4 figure, I would suggest doing a 4x2 figure, thus making it possible to have bigger text.

**Comment by krober10nd** [comment]
Okay, yes that's a good point about the BP2004 benchmark.

Re layout: I'll switch the tick labels and try out the 4x2 figure. I'll post it here for your opinion.

**Comment by krober10nd** [comment]
Changed to consistent xtick label format, Increased font size of all labels to 19 (from 18) and switched layout to 4x2.

![Performance_V5](https://user-images.githubusercontent.com/18619644/98286216-68d60c80-1f82-11eb-97a7-a6ce97e403c7.png)

**Comment by jorgensd** [comment]
This figure seems alot better. Make sure that the ticks is sufficiently large by trying to print it once embedded in the paper. As the margins of the Joss-paper template is quite wide, it crops the images quite a bit.

Another note: You claim in your comparison that the average cell quality affects the condition number of a corresponding fem matrix more than the minimal quality. Do you have any references for this claim?

**Comment by krober10nd** [comment]
> Another note: You claim in your comparison that the average cell quality affects the condition number of a corresponding fem matrix more than the minimal quality. Do you have any references for this claim?

I did not claim that the mean quality affects the cell quality *more* than the minimum cell quality. I said 

"...With that said, SeismicMesh produces higher mean cell qualities by about 5-10% as compared to gmsh and cgal, which leads to reduced finite element matrix condition numbers..."

My claim is asserted based on the following two pieces:

1) From @nschloe [comparison's](https://github.com/nschloe/meshgen-comparison),  the number of iterations used to solve a Poisson problem is fewer/equivalent for SM *despite the observation* that the *minimum* quality is lower for SM than `gmsh` in several problems (disk, ball, L-shape, etc.) but the mean cell quality is higher. 

2) The CG's convergence rate is directly influenced by the condition number of the matrix. I don't have a reference immediately for this derivation but this derivation does appear on Wikipedia for what it's worth (https://en.wikipedia.org/wiki/Conjugate_gradient_method under convergence properties).

**Comment by krober10nd** [comment]
Perhaps if I stated:

> "...With that said, SeismicMesh produces higher mean cell qualities by about 5-10% as compared to gmsh and cgal, which can lead to better performance when solving elliptical partial differential equations..."

**Comment by nschloe** [comment]
> The CG's convergence rate is directly influenced by the condition number of the matrix.

The matter is more complicated than that. I wouldn't bring the the word _condition number_ in.

**Comment by krober10nd** [comment]
> The matter is more complicated than that. I wouldn't bring the the word condition number in.


Yea I agree with that. 

Section 3 of "What is a good finite element?" summarizes the complex problem well. I'll drop the clause about the performance of solvers as a function of mesh quality then as it depends on many factors according to the reference. 

All I can say really based on the results is that the mean mesh quality is larger in SM and this appears fairly consistently. Other conclusions can be drawn by the reader in more application-based studies down the line. 

http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.67.5835

**Comment by jorgensd** [comment]
As another side-note: To run the performance tests, it is required to have several packages not installed by SeismicMesh, such as `meshplex`. I would suggest adding these to an `extras` in the `setup.py`:
Example from: https://godatadriven.com/blog/a-practical-guide-to-using-setup-py/
```
setup(
    name='example',
    version='0.1.0',
    packages=find_packages(include=['exampleproject', 'exampleproject.*']),
    install_requires=[
        'PyYAML',
        'pandas==0.23.3',
        'numpy>=1.14.5'
    ],
    extras_require={
        'interactive': ['matplotlib>=2.2.0,, 'jupyter'],
    }
)
```

**Comment by krober10nd** [comment]
I guess this can be closed now?
