### ISSUE TITLE
constant cell_size not working

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#69]
Much to my surprise, a simple example like
```python
import SeismicMesh

disk = SeismicMesh.Circle(0.0, 0.0, 1.0)
points, cells = SeismicMesh.generate_mesh(domain=disk, cell_size=0.1)
```
fails with
```
ValueError: `cell_size` must either be a function or a `cell_size` object
```
This should probably be fixed.

**Comment by krober10nd** [comment]
yea sorry I guess I missed the case with the scalar sizing field.

**Comment by krober10nd** [comment]
Okay, using the PR #73 I've added support for constant cell-sizes I also added some README examples (that `exdown` passes over) to make sure that the presented API doesn't break.. 

https://github.com/krober10nd/SeismicMesh/tree/const_cell_size

A disk: 
```
import SeismicMesh
import meshio
 
disk = SeismicMesh.disk(0.0, 0.0, 1.0)
points, cells = SeismicMesh.generate_mesh(domain=disk, cell_size=0.1)
meshio.write_p
oints_cells(
    "disk.vtk",
    points,
    [("triangle", cells)],
    file_format="vtk",
)
```
![Disk](https://user-images.githubusercontent.com/18619644/95608173-1f51da80-0a33-11eb-90be-170beda85b5a.png)


A rectangle: 
```
import SeismicMesh
import meshio
 
rect = SeismicMesh.Rectangle((0.0, 1.0, 0.0, 1.0))
points, cells = SeismicMesh.generate_mesh(domain=rect, cell_size=0.1)
meshio.write_points_cells(
    "rectangle.vtk",
    points,
    [("triangle", cells)],
    file_format="vtk",
)
```
![Rect](https://user-images.githubusercontent.com/18619644/95607603-5d023380-0a32-11eb-9c6f-41fac9e00aa7.png)
A cuboid 

```
 import SeismicMesh
 import meshio
 
 cube = SeismicMesh.Cube((0.0, 1.0, 0.0, 1.0, 0.0, 1.0))
 points, cells = SeismicMesh.generate_mesh(domain=cube, cell_size=0.1)
 meshio.write_points_cells(
     "cube.vtk",
     points,
     [("tetra", cells)],
     file_format="vtk",
 )
```

![cube](https://user-images.githubusercontent.com/18619644/95607827-a94d7380-0a32-11eb-9601-7677edd2febb.png)

**Comment by krober10nd** [comment]
I since fixed the cube quality by using a "better" initial point formation in 3d (I updated the panel too on the README).
