### ISSUE TITLE
generate_mesh: verbose=False

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#70]
By default, `generate_mesh` prints lots of intermediate stats,
```
[...]
Iteration #43, max movement is 0.010014, there are 367 vertices and 678 cells
     Elapsed wall-clock time 0.001311 :
Iteration #44, max movement is 0.010025, there are 367 vertices and 678 cells
     Elapsed wall-clock time 0.001292 :
Iteration #45, max movement is 0.010035, there are 367 vertices and 678 cells
     Elapsed wall-clock time 0.001268 :
Iteration #46, max movement is 0.010043, there are 367 vertices and 678 cells
     Elapsed wall-clock time 0.001271 :
[...]
```
It'd be very useful if it was possible to disable this. This is typically done by a `verbose` argument. (Usually, this defaults to `False`, too.)

**Comment by krober10nd** [comment]
I have the option `nscreen` which controls this output frequency.

**Comment by nschloe** [comment]
Okay. What do I have to set it to to silence SM? `0` just throws an error.

**Comment by krober10nd** [comment]
Ah okay. I had made `nscreen` larger than the `max_iter` to avoid the intermediate info but I can switch this to a verbose to completely silence all output.

**Comment by nschloe** [comment]
Perhaps you can add `verbose` if someone else `nscreens` for something.

**Comment by krober10nd** [comment]
Is this a pun? 👍

**Comment by krober10nd** [comment]
I think you mean if I the user specifies an `nscreen` then there's an additional `vebose` catch?

**Comment by nschloe** [comment]
I meant to say that you don't necessarily have to remove `nscreens`. I don't know if there's any use for it if there's a `verbose` option, but at least you yourself found it useful once.

**Comment by krober10nd** [comment]
yea I agree. It's more logical and easier to understand to just have a 'verbose' option.
