### ISSUE TITLE
"cell_size"?

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#75]
The main controlling variable for cell size is `cell_size`. Does this represent the cell area? Or the edge length? (I can't find it from the code.) If the latter, the variable should probably be renamed. Documentation should also be clear on this.

**Comment by krober10nd** [comment]
Yea I’ve been following your discussions with the cgal and gmsh folks and it seems quite confusing with naming these stuff 


It seems the cell_size in SeismicMesh  should be called edgelength as the algorithm compares the length of the edges against the sizing map and then extends bars accordingly

**Comment by krober10nd** [comment]
Also, I believe I need to update pygalmesh and redo the benchmark for the disk. I saw that there was some zero element sizes in that mesh causing a minimum quality of zero.

**Comment by nschloe** [comment]
Indeed, I fixed something for 2D meshes. It's important to always side the software versions, too, so we don't get confused in the future. (That's why I asked about `SeismicMesh.__version__`, too.) pygalmesh returns the CGAL version under `__cgal_version__`.

**Comment by krober10nd** [comment]
in #77 renamed `cell_size` to `edge_length`, edited docstrings, tests, readthedocs website and benchmarks.
