### ISSUE TITLE
still too verbose

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#80]
Even though I set `verbose=False`, I'm still getting
```
Commencing mesh generation with 4 vertices on rank 0.
Termination reached...maximum number of iterations reached.
```

**Comment by nschloe** [comment]
There are more `print()`s in `sliver_removal`, too. Best grep your codebase for `print`.

**Comment by krober10nd** [comment]
Yea I left this on purpose because I wanted some feedback to the user to see something was working.

**Comment by nschloe** [comment]
Alright. It should be possible to turn off entirely though. Perhaps, instead of 'verbose', you could use a 'verbosity' integer level.

**Comment by krober10nd** [comment]
Yea that's reasonable.

**Comment by krober10nd** [comment]
so, verbose = 0 (default) which tells you it's starting and finishing, verbose=-1 (nothing), verbose > 0 (prints intermediate output every iterations%verbose steps.

**Comment by nschloe** [comment]
`verbosity` would typically be a nonnegative integer where `0` means "nothing".

**Comment by krober10nd** [comment]
I just need to reinsert the 'flush' in the prints for visibility in parallel.

**Comment by nschloe** [comment]
I'm getting
```
Termination reached...maximum number of iterations reached.
Deleting 0 poor quality boundary entities...
Movement tolerance reached after 6 iterations..exiting
Constraining 4 fixed points..
Commencing mesh generation with 1839 vertices on rank 0.
Termination reached...maximum number of iterations reached.
Deleting 0 poor quality boundary entities...
Movement tolerance reached after 6 iterations..exiting
Constraining 4 fixed points..
Commencing mesh generation with 2423 vertices on rank 0.
Termination reached...maximum number of iterations reached.
Deleting 1 poor quality boundary entities...
Movement tolerance reached after 6 iterations..exiting
Constraining 4 fixed points..
Commencing mesh generation with 3278 vertices on rank 0.
Termination reached...maximum number of iterations reached.
Deleting 0 poor quality boundary entities...
Movement tolerance reached after 9 iterations..exiting
Constraining 4 fixed points..
Commencing mesh generation with 4479 vertices on rank 0.
Termination reached...maximum number of iterations reached.
Deleting 2 poor quality boundary entities...
Movement tolerance reached after 8 iterations..exiting
```
again with `verbosity=0`.

**Comment by krober10nd** [comment]
Hm. I get the corner constraint message. I forgot to put the verbose in there. But the other ones I don't get. I actually tried to anticipate this and make both those functions take the verbose integer (delete_boundary_entities) and (laplacian2) in geometry.utils 

Maybe verbose == 0 doesn't evaluate to False on some versions of Python?  

Anyway I'll make a test for this so it doesn't happen again.

**Comment by krober10nd** [comment]
>>> import SeismicMesh
>>> SeismicMesh.__version__
'3.1.4'
>>> 

```
points, cells = SeismicMesh.generate_mesh(domain=disk, edge_length=0.1, verbose=0)
```

(base) keiths-MacBook-Pro:SeismicMesh Keith$ python disk.py 
(base) keiths-MacBook-Pro:SeismicMesh Keith$ 

```
 points, cells = SeismicMesh.generate_mesh(domain=disk, edge_length=0.1, verbose=1)
```

(base) keiths-MacBook-Pro:SeismicMesh Keith$ python disk.py 
Constraining 0 fixed points..
Commencing mesh generation with 327 vertices on rank 0.
Termination reached...maximum number of iterations reached.
Deleting 0 poor quality boundary entities...
Movement tolerance reached after 5 iterations..exiting
(base) keiths-MacBook-Pro:SeismicMesh Keith$ 



```
 points, cells = SeismicMesh.generate_mesh(domain=disk, edge_length=0.1, verbose=2)
```
...
Iteration #48, max movement is 0.016383, there are 327 vertices and 596 cells
     Elapsed wall-clock time 0.002237 : 
Iteration #49, max movement is 0.016350, there are 327 vertices and 596 cells
     Elapsed wall-clock time 0.002149 : 
Termination reached...maximum number of iterations reached.
Deleting 0 poor quality boundary entities...
Movement tolerance reached after 5 iterations..exiting

**Comment by krober10nd** [comment]
Well, I put in a unit test for this and it passed. The test directs all stdout to a file and then measures the size of that file for different verbosity levels. 

Not sure how you're calling the program that's creating these messages...

**Comment by nschloe** [comment]
Thanks for the investigation. You were right, I missed a `verbose=0`. [Fixed now](https://github.com/nschloe/meshgen-comparison/commit/2051274045a9f99e891751680544d0420d750e45).

**Comment by krober10nd** [comment]
Cool. Looks like the additional Laplacian smooth at the end really helps boost the minimum element qualities in 2d.
