### ISSUE TITLE
domain + bounding box, Disk arguments.

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#81]
For many domains and domain combinations the bounding box can be computed internally. This saves the `bounding_box` argument. For example, instead of
```python
bbox = (-1.0, 1.0, -1.0, 1.0)
disk = SeismicMesh.geometry.Disk(0, 0, 1)
 points, cells = SeismicMesh.generate_mesh(
     bbox=bbox,
     h0=h,
     domain=disk,
     edge_length=h
 )
```
one could have
```python
disk = SeismicMesh.geometry.Disk(0, 0, 1)
 points, cells = SeismicMesh.generate_mesh(
     h0=h,
     domain=disk,
     edge_length=h
 )
```
This requires the `Disk` object to have a member `bbox` which can be computed easily from the input values.

Also, I would probably make the arguments of `Disk` and array of length 2 and a scalar, not three scalars. With `Disk([0.2, 0.1], 1.5)`, it's clear at first glance what the arguments mean. With `Disk(0.2, 0.1, 1.5)` not so much.

**Comment by krober10nd** [comment]
In regard to the first comment, disk indeed already has a bbox that is unpacked. 

In regard to the second comment: okay.

**Comment by krober10nd** [comment]
See geometry.signed_distance_functions.py
